Repository chronoscio/backend, pull requests merged in 2018-10, with the labels that each got.

#43 Update to Django 2.1
  config/requirements.txt
Labels: kind/security, status/waits for review

#37 Allow the territory api to exclude by id
  config/requirements.txt
  project/api/factories.py
  project/api/filters.py
  project/api/tests.py
  project/api/views.py
  project/interactivemap/settings.py
Labels: status/reviewed

#46 Allow tests to be run with -k
  Makefile
  project/api/tests.py
Labels: status/reviewed

#49 Remove non-null constraint from ArrayField
  project/api/migrations/0017_auto_20181008_2028.py
  project/api/migrations/0018_auto_20181008_2226.py
  project/api/migrations/0019_auto_20181009_0401.py
  project/api/migrations/0020_auto_20181009_0403.py
  project/api/migrations/0021_auto_20181009_1033.py
  project/api/models.py
  project/interactivemap/settings.py
Labels: status/reviewed

#30 Entity & PoliticalEntity models
  config/requirements.txt
  docs/DEVELOPER.md
  docs/example_db_dump.json
  project/api/admin.py
  project/api/factories.py
  project/api/filters.py
  project/api/migrations/0001_initial.py
  project/api/migrations/0002_auto_20180720_0022.py
  project/api/migrations/0002_auto_20180923_1823.py
  project/api/migrations/0003_auto_20180726_1831.py
  project/api/migrations/0003_auto_20181004_0442.py
  project/api/migrations/0004_auto_20180726_1851.py
  project/api/migrations/0004_auto_20181011_0231.py
  project/api/migrations/0005_auto_20180801_0040.py
  project/api/migrations/0006_auto_20180801_2103.py
  project/api/migrations/0007_auto_20180808_0543.py
  project/api/migrations/0008_auto_20180809_0242.py
  project/api/migrations/0009_auto_20180809_0332.py
  project/api/migrations/0010_auto_20180810_0139.py
  project/api/migrations/0011_auto_20180814_0310.py
  project/api/migrations/0012_auto_20180903_0156.py
  project/api/migrations/0013_auto_20180903_0156.py
  project/api/migrations/0014_auto_20180911_0518.py
  project/api/migrations/0015_auto_20180912_0109.py
  project/api/migrations/0016_auto_20180914_0433.py
  project/api/migrations/0017_auto_20181008_2028.py
  project/api/migrations/0018_auto_20181008_2226.py
  project/api/migrations/0019_auto_20181009_0401.py
  project/api/migrations/0020_auto_20181009_0403.py
  project/api/models.py
  project/api/permissions.py
  project/api/serializers.py
  project/api/tests.py
  project/api/urls.py
  project/api/user.py
  project/api/views.py
  project/interactivemap/settings.py
  project/manage.py
  project/wait_for_pg.py
Labels: priority/critical, status/reviewed

#55 Geobuf compression on api response
  config/requirements.txt
  project/api/serializers.py
  project/api/tests.py
Labels: kind/API, status/waits for review

#57 Linting in Travis
  .autopep8.py
  .pylint.py
  .travis.yml
  Makefile
  config/requirements.txt
  project/api/apps.py
  project/api/filters.py
  project/api/migrations/0005_fix_migration_warning.py
  project/api/models.py
  project/api/permissions.py
  project/api/serializers.py
  project/api/tests.py
  project/api/urls.py
  project/api/user.py
  project/api/views.py
  project/interactivemap/settings.py
  project/interactivemap/urls.py
  project/manage.py
  project/wait_for_pg.py
Labels: status/waits for review

#64 Admin page metadata
  project/api/admin.py
Labels: status/reviewed

#63 Add sign up form
  project/api/templates/signup.html
  project/api/urls.py
  project/api/views.py
Labels: kind/feature, kind/security, status/reviewed

#61 Added ability to upload shape files for territories on admin panel
  config/nginx/django.conf
  project/api/admin.py
  project/api/forms.py
  project/api/migrations/0006_auto_20181023_1809.py
  project/api/migrations/0007_auto_20181025_0248.py
  project/api/models.py
Labels: kind/feature, status/reviewed

#65 Fix ValidationError upon editing territory
  project/api/models.py
Labels: kind/bug, status/reviewed

#66 Auto-generated model documentation
  config/requirements.txt
  project/interactivemap/settings.py
  project/interactivemap/urls.py
Labels: kind/documentation, status/waits for review
