Repository chronoscio/backend, pull requests merged in 2018-08, with the labels that each got.

#6 Move API from GraphQL to REST
  .gitignore
  config/requirements.txt
  project/api/migrations/0003_auto_20180726_1831.py
  project/api/migrations/0004_auto_20180726_1851.py
  project/api/migrations/0005_auto_20180801_0040.py
  project/api/migrations/0006_auto_20180801_2103.py
  project/api/migrations/0007_auto_20180808_0543.py
  project/api/migrations/0008_auto_20180809_0242.py
  project/api/migrations/0009_auto_20180809_0332.py
  project/api/models.py
  project/api/schema.py
  project/api/serializers.py
  project/api/tests.py
  project/api/urls.py
  project/api/views.py
  project/interactivemap/schema.py
  project/interactivemap/settings.py
  project/interactivemap/urls.py
Labels: kind/API, priority/critical, status/reviewed

#9 Add line-break on received certificate
  project/interactivemap/settings.py
Labels: status/waits for review

#10 Auth0 Authentication
  .travis.yml
  Dockerfile
  Makefile
  README.md
  config/requirements.txt
  django.env.sample
  project/api/helpers.py
  project/api/migrations/0010_auto_20180810_0139.py
  project/api/migrations/0011_auto_20180814_0310.py
  project/api/models.py
  project/api/permissions.py
  project/api/serializers.py
  project/api/tests.py
  project/api/urls.py
  project/api/user.py
  project/api/views.py
  project/interactivemap/settings.py
Labels: kind/API, kind/security, status/waits for review

#11 Fix readme for new project name
  README.md
Labels: status/reviewed

#14 Contribution guidelines
  CONTRIBUTING.md
  DEVELOPER.md
  README.md
Labels: kind/documentation, status/reviewed

#13 Fix travis build
  .autopep8.py
  .pylint.py
  .travis.yml
  .vscode/settings.json
  config/requirements.txt
  django.env.sample
  project/api/models.py
  project/api/tests.py
Labels: status/reviewed

#15 Allow querying based on bounds parameter
  config/requirements.txt
  project/api/models.py
  project/api/tests.py
  project/api/views.py
  project/interactivemap/urls.py
Labels: status/reviewed
